# Generated by Django 4.2.7 on 2025-12-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('posture', models.CharField(blank=True, max_length=50, null=True)),
                ('gait_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('size_category', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_weight', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('is_lame', models.BooleanField(blank=True, null=True)),
                ('lameness_probability', models.FloatField(blank=True, null=True)),
                ('lameness_confidence', models.FloatField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('diagnosis_note', models.TextField(blank=True, null=True)),
                ('analysis_video_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'database_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('estimated_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'database_animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('dry_matter', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('price_per_kg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'database_feed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LamenessAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('is_lame', models.BooleanField(blank=True, null=True)),
                ('lameness_probability', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('diagnosis_note', models.TextField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='analysis/results/')),
                ('plot_file', models.FileField(blank=True, null=True, upload_to='analysis/plots/')),
                ('annotated_video', models.FileField(blank=True, null=True, upload_to='analysis/videos/')),
                ('h5_file', models.FileField(blank=True, null=True, upload_to='analysis/data/')),
                ('analysis_log', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Анализ хромоты',
                'verbose_name_plural': 'Анализы хромоты',
                'db_table': 'database_lameness_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('ration_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_dmi', models.FloatField(blank=True, null=True)),
                ('energy_content', models.FloatField(blank=True, null=True)),
                ('calculation_date', models.DateTimeField(blank=True, null=True)),
                ('composition', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'database_ration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role_id', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'database_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('resolution', models.CharField(max_length=50)),
                ('analysis_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'database_video',
                'managed': False,
            },
        ),
    ]
